# Write a workflow that installs dependancies and runs the test. Specify a default folder for all the steps inside the job.

name: Test Node
on:
  push:

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./node-app
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: ls -al
        - run: npm install
        - run: npm test